name: "06 - Contexts"
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        type: boolean
        required: false
        default: false
env:
    MY_WORKFLOW_VAR: "global"
    MY_OVERWRITTEN_VAR: "global"
jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "job"
      MY_OVERWRITTEN_VAR: "job"
    steps:
      - name: Display Information
        run: |
          echo "Event name ${{ github.event_name }}; Ref: ${{ github.ref }}; SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}; Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}; Run Number: ${{ github.run_number }}"
      - name: Retrieve Variable
        run: echo "The value of my var is ${{ vars.MY_VAR }}"
      - name: Print Env Variables
        env:
          MY_OVERWRITTEN_VAR: "step"
        run: |
          echo "MY_WORKFLOW_VAR: $MY_WORKFLOW_VAR"
          echo "MY_OVERWRITTEN_VAR: $MY_OVERWRITTEN_VAR"
          echo "MY_VAR: $MY_VAR"