name: 08 - Using Variables
run-name: Using Variables
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  WORKFLOW_VAR: "I am a workflow env variable"
  OVERWRITTEN: "I will be overwritten"
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env variable"
      OVERWRITTEN: "I have been overwritten at job level"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am a step env variable"
          step_var2: "I am another step env variable"
        run: |
          echo "Step env var: $STEP_VAR"
          echo "Step env var 2: $step_var2"
          echo "Job env var: $JOB_VAR"
          echo "Workflow env var: $WORKFLOW_VAR"
          echo "Overwritten at job level: $OVERWRITTEN"
      - name: Overwrite Job Variable
        env:
          OVERWRITTEN: "I have been overwritten at step level"
        run: echo "Step env var $OVERWRITTEN"