name: 08 - Using Variables
run-name: Using Variables
on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
env:
  WORKFLOW_VAR: "Workflow Environment Variable Value"
  OVERWRITTEN: "Overwritten Workflow Environment Variable Value"
  UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'default value' }}
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job Environment Variable Value"
      OVERWRITTEN: "Overwritten Job Environment Variable Value"
    steps:
      - name: Print environment variable
        env:
          STEP_VAR: "Step Environment Variable Value"
          STEP_VAR2: "Step Environment Variable(2) Value"
        run: |
          echo "Step environment variable: [ $STEP_VAR ]"
          echo "Step environment variable (2): [ ${{ env.STEP_VAR2 }} ]"
          echo "Job environment variable: [ $JOB_VAR ]"
          echo "Workflow environment variable: [ $WORKFLOW_VAR ]"
          echo "Overwritten environment variable: [ $OVERWRITTEN ]"
      - name: Overwrite job variable
        env:
          OVERWRITTEN: "Overwritten Step Environment Variable Value"
        run: |
          echo "Overwritten environment variable: [ $OVERWRITTEN ]"
  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
          echo "Repository variable: [ ${{ vars.REPOSITORY_VAR }} ]"
  echo-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print prod variables
        run: |
          echo "Repository variable: [ ${{ vars.REPOSITORY_VAR }} ]"
          echo "Environment variable: [ ${{ vars.TARGET_VAR }} ]"
  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print undefined variables
        run: |
          echo "Undefined variable: [ ${{ env.UNDEFINED_VAR_WITH_DEFAULT }} ]"
